### ISSUE TITLE
Rename `keybase revoke` to `keybase remove-key`

### ISSUE THREAD

**Issue by maxtaco** [keybase/node-client#131]
It's scary to call it revoking when we're not generating a PGP revocation certificate.  See keybase/keybase-issues#133 for an example of a confusion here.

**Comment by frankcash** [comment]
I'm working on this but before I push I want to make sure I didn't break any tests.

I run `npm test` in the root directory and get the following output:

```
$ npm test

> keybase@0.8.16 test /Users/{myUser}/Desktop/node-client
> make test

(cd test && ../node_modules/.bin/iced run.iced)
warn: No config file given, and none found in ~/.node_client_test.json; using defaults
info: Alice wasn't found!
✔ 0_alice.iced: generate
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: This socket is closed.
  at Socket._writeGeneric (net.js:647:19)
  at Socket._write (net.js:700:8)
  at doWrite (_stream_writable.js:301:12)
  at writeOrBuffer (_stream_writable.js:288:5)
  at Socket.Writable.write (_stream_writable.js:217:11)
  at Socket.write (net.js:625:40)
  at BufferInStream.ondata (_stream_readable.js:540:20)
  at BufferInStream.emit (events.js:107:17)
  at BufferInStream.Readable.read (_stream_readable.js:373:10)
  at flow (_stream_readable.js:750:26)
  at resume_ (_stream_readable.js:730:3)
  at _stream_readable.js:717:7
  at process._tickCallback (node.js:355:11)

make: *** [test] Error 1
npm ERR! Test failed.  See above for more details.
```

The same error occurs on both my edited branch and an unedited branch.

**Comment by frankcash** [comment]
Okay I updated `revoke.iced` to alias to `remove` as well as changed the dialogue to ` DANGER ZONE! Really remove your key and cancel all signatures [y/N] ` (as well as the test function in `user.iced`).  But all of this (prompt and cmd alias) is done in `revoke.iced` would it make sense to change the file to `remove.iced` then?

**Comment by frankcash** [comment]
:construction_worker:  @maxtaco
