### ISSUE TITLE
'already registered' signup retries hit an exception

### ISSUE THREAD

**Issue by oconnor663** [keybase/node-client#188]
```
warn: No config file found; tried '/tmp/tmp.4dYZByB2Lt/.config/keybase/config.json'
Your email: asdkjfhkad@oidjdfg.com
Invitation code (leave blank if you don't have one): 202020202020202020202020
Your desired username: t79
Your login passphrase: ************
Repeat to confirm: ************
- run scrypt [==================================] 100%
error: Username 't79' already registered
Your email: asdkjfhkad@oidjdfg.com
Invitation code (leave blank if you don't have one): 202020202020202020202020
Your desired username: t81
Your login passphrase: (<default hidden>) ************
Repeat to confirm: ************
_http_outgoing.js:333
    throw new Error('"name" and "value" are required for setHeader().');
          ^
Error: "name" and "value" are required for setHeader().
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:333:11)
    at new ClientRequest (_http_client.js:101:14)
    at Object.exports.request (http.js:49:10)
    at Request.start (/usr/lib/node_modules/keybase/node_modules/request/request.js:583:30)
    at Request.write (/usr/lib/node_modules/keybase/node_modules/request/request.js:1232:28)
    at /usr/lib/node_modules/keybase/node_modules/request/request.js:403:14
    at process._tickCallback (node.js:355:11)
```

**Comment by maxtaco** [comment]
Also an issue [here](https://github.com/keybase/keybase-issues/issues/1526)
