### ISSUE TITLE
trying to push secret gives me TypeError

### ISSUE THREAD

**Issue by oconnor663** [keybase/node-client#215]
```
$ nkb push --secret
make: Nothing to be done for 'default'.
info: Public key already uploaded; pushing only secret key
buffer.js:67
    throw new TypeError('must start with number, buffer, array or string');
    ^
TypeError: must start with number, buffer, array or string
    at new Buffer (buffer.js:67:11)
    at KeyManager.exports.KeyManager.KeyManager.get_tsenc (/home/jacko/node-client/lib/keymanager.js:257:16)
    at /home/jacko/node-client/lib/keymanager.js:387:28
    at /home/jacko/node-client/lib/keymanager.js:397:13
    at Deferrals.exports.Deferrals.Deferrals._call (/home/jacko/node-client/node_modules/iced-runtime/lib/runtime.js:86:16)
    at /home/jacko/node-client/node_modules/iced-runtime/lib/runtime.js:98:26
    at exports.trampoline.trampoline (/home/jacko/node-client/node_modules/iced-runtime/lib/runtime.js:64:14)
    at Deferrals.exports.Deferrals.Deferrals._fulfill (/home/jacko/node-client/node_modules/iced-runtime/lib/runtime.js:96:16)
    at ret (/home/jacko/node-client/node_modules/iced-runtime/lib/runtime.js:29:18)
    at /home/jacko/node-client/node_modules/iced-error/index.js:92:22
```

**Comment by maxtaco** [comment]
Can you make a jira ticket for this?  Thanks

**Comment by oconnor663** [comment]
https://keybase.atlassian.net/browse/CORE-1936
