### ISSUE TITLE
Missing cheerio module in fresh npm installation

### ISSUE THREAD

**Issue by felixonmars** [keybase/node-client#217]
Not sure if it's a problem of npm or keybase, though. It used to work and I have packaged a working version for Arch, but a rebuild will break it now.

To reproduce:

```
felix@flygon /tmp/test-keybase {0}$ npm install keybase
/tmp/test-keybase
`-- keybase@0.8.23
  +-- cheerio@0.13.0
  | `-- htmlparser2@3.4.0
  |   `-- readable-stream@1.1.12
  |     `-- string_decoder@0.10.31
  +-- keybase-installer@1.0.2
  | `-- request@2.58.0
  |   `-- bl@0.9.4
  |     `-- readable-stream@1.0.33
  |       `-- string_decoder@0.10.31
  +-- read@1.0.5  (git://github.com/keybase/read.git#740ae6a1a72a96984ae3527eb0ce0066c9fc8d47)
  | `-- mute-stream@0.0.5
  `-- request@2.58.0
    `-- bl@0.9.4
      `-- readable-stream@1.0.33
        `-- string_decoder@0.10.31

npm WARN ENOENT ENOENT: no such file or directory, open '/tmp/test-keybase/package.json'
npm WARN EPACKAGEJSON test-keybase No description
npm WARN EPACKAGEJSON test-keybase No repository field.
npm WARN EPACKAGEJSON test-keybase No README data
npm WARN EPACKAGEJSON test-keybase No license field.
npm WARN EBUNDLEOVERRIDE Replacing bundled keybase > read with new installed version
npm WARN EBUNDLEOVERRIDE Replacing bundled keybase > cheerio with new installed version
felix@flygon /tmp/test-keybase {0}$ ./node_modules/.bin/keybase id felixonmars
module.js:339
    throw err;
    ^

Error: Cannot find module 'cheerio'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/tmp/test-keybase/node_modules/keybase/lib/sigchain.js:32:13)
    at Object.<anonymous> (/tmp/test-keybase/node_modules/keybase/lib/sigchain.js:923:4)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
```

**Comment by didyouexpectthat** [comment]
I had same problem on Windows.

**Comment by felixonmars** [comment]
This turns out to be an npm issue (https://github.com/npm/npm/issues/10482). Sorry for the noise.
